---
  # Setup Mariadb on Centos
- import_playbook: database.yml

  # Setup httpd webserver on Centos
- import_playbook: webserver.yml

  # execute setup of DB replication if more than one DB host found. Means there are two DCs.
- import_playbook: dbrepl.yml
  when: ( ( groups['database'] | length ) == 2 )
