---
- name: Install WordPress, MariaDB, and PHP-FPM
  hosts: tag_Name_webserver
  remote_user: ec2-user
  become: true
  become_method: sudo

  roles:
    - common
    - mariadb
    - php-fpm
    - wordpress
